spring:
  application:
    name: smarTest-backend

  datasource:
    url: jdbc:mysql://localhost:3306/smartest_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

server:
  port: 8081

app:
  jwt:
    secret: SmArTeSt_S3cr3t_K3y_2026_ENSA_ChangeMe!
    expiration: 86400000

  websocket:
    allowed-origins: http://localhost:5173