sonar.projectKey=smartest
sonar.projectName=SmarTest
sonar.projectVersion=1.0

# SonarCloud
sonar.host.url=https://sonarcloud.io
sonar.organization=oumeyma-elaammari

# Root
sonar.sourceEncoding=UTF-8

# Multi-stack sources
sonar.sources=packages/smartest-backend/src/main,packages/smartest-web/src,packages/smartest-desktop
sonar.tests=packages/smartest-backend/src/test

# Language-specific hints
sonar.java.binaries=packages/smartest-backend/target/classes

# Global exclusions (generated/build artifacts)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.next/**,**/target/**,**/bin/**,**/obj/**,**/*.min.js,**/*.Designer.cs
sonar.test.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/bin/**,**/obj/**
