#pragma checksum "..\..\Views\ExamenSupervisionDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DA3649F7D1975A21C0AC59FF9B769870D1460F14"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace smartest_desktop.Views {
    
    
    /// <summary>
    /// ExamenSupervisionDialog
    /// </summary>
    public partial class ExamenSupervisionDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtTitle;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtQuestion;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtTemps;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtErreur;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtListeParticipantsTitre;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSalleAttenteCount;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox ListAttente;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtApercu;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnDemarrer;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPause;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnReprendre;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPrecedente;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSuivante;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTempsMoins;
        
        #line default
        #line hidden
        
        
        #line 86 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTempsPlus;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\Views\ExamenSupervisionDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTerminer;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.5.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/smartest-desktop;component/views/examensupervisiondialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Views\ExamenSupervisionDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.5.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 14 "..\..\Views\ExamenSupervisionDialog.xaml"
            ((smartest_desktop.Views.ExamenSupervisionDialog)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TxtTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TxtQuestion = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TxtTemps = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.TxtErreur = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.TxtListeParticipantsTitre = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.TxtSalleAttenteCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.ListAttente = ((System.Windows.Controls.ListBox)(target));
            return;
            case 9:
            this.TxtApercu = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.BtnDemarrer = ((System.Windows.Controls.Button)(target));
            
            #line 70 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnDemarrer.Click += new System.Windows.RoutedEventHandler(this.BtnDemarrer_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.BtnPause = ((System.Windows.Controls.Button)(target));
            
            #line 73 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnPause.Click += new System.Windows.RoutedEventHandler(this.BtnPause_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnReprendre = ((System.Windows.Controls.Button)(target));
            
            #line 76 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnReprendre.Click += new System.Windows.RoutedEventHandler(this.BtnReprendre_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.BtnPrecedente = ((System.Windows.Controls.Button)(target));
            
            #line 79 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnPrecedente.Click += new System.Windows.RoutedEventHandler(this.BtnPrecedente_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.BtnSuivante = ((System.Windows.Controls.Button)(target));
            
            #line 82 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnSuivante.Click += new System.Windows.RoutedEventHandler(this.BtnSuivante_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.BtnTempsMoins = ((System.Windows.Controls.Button)(target));
            
            #line 85 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnTempsMoins.Click += new System.Windows.RoutedEventHandler(this.BtnTempsMoins_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.BtnTempsPlus = ((System.Windows.Controls.Button)(target));
            
            #line 88 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnTempsPlus.Click += new System.Windows.RoutedEventHandler(this.BtnTempsPlus_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BtnTerminer = ((System.Windows.Controls.Button)(target));
            
            #line 91 "..\..\Views\ExamenSupervisionDialog.xaml"
            this.BtnTerminer.Click += new System.Windows.RoutedEventHandler(this.BtnTerminer_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

